// <auto-generated />
using System;
using Meetup.ApplicationDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Meetup.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210809103445_Update_WorkExprence")]
    partial class Update_WorkExprence
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Meetup.ApplicationDbContext.Model.MeetupLocation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndFreeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsFreeTime")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartFreeTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("MeetupLocations");
                });

            modelBuilder.Entity("Meetup.ApplicationDbContext.Model.Meetups", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double>("DurationMeetup")
                        .HasColumnType("double precision");

                    b.Property<byte[]>("Images")
                        .HasColumnType("bytea");

                    b.Property<string>("MeetupLocationId")
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MeetupLocationId");

                    b.ToTable("Meetups");
                });

            modelBuilder.Entity("Meetup.ApplicationDbContext.Model.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Age")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Prof")
                        .HasColumnType("text");

                    b.Property<string>("WorkExperience")
                        .HasColumnType("text");

                    b.Property<bool>("WorkHas")
                        .HasColumnType("boolean");

                    b.Property<string>("WorkPosition")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MeetupsUser", b =>
                {
                    b.Property<string>("MeetupsId")
                        .HasColumnType("text");

                    b.Property<string>("UsersId")
                        .HasColumnType("text");

                    b.HasKey("MeetupsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("MeetupsUser");
                });

            modelBuilder.Entity("Meetup.ApplicationDbContext.Model.Meetups", b =>
                {
                    b.HasOne("Meetup.ApplicationDbContext.Model.MeetupLocation", "MeetupLocation")
                        .WithMany("Meetups")
                        .HasForeignKey("MeetupLocationId");

                    b.Navigation("MeetupLocation");
                });

            modelBuilder.Entity("MeetupsUser", b =>
                {
                    b.HasOne("Meetup.ApplicationDbContext.Model.Meetups", null)
                        .WithMany()
                        .HasForeignKey("MeetupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meetup.ApplicationDbContext.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Meetup.ApplicationDbContext.Model.MeetupLocation", b =>
                {
                    b.Navigation("Meetups");
                });
#pragma warning restore 612, 618
        }
    }
}
